name: CI

# Run on master, tags, or any pull requests
on:
  push:
    branches: [master]
    tags: ["*"]

  pull_request:

jobs:
  test:
    name: Go - ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.21"  # earliest version required by dependencies; writetlds.go uses the `slices` package, which was added in this version
          - "1.22"  # Relatively recent version
          - "stable"  # Latest stable version
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
          - x86 # 32-bit; i686
    # env:
      # CGO_ENABLED: 0
    steps:
      - name: Checkout package
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}

      - name: Run all tests
        run: go test -v ./...
